# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dimasmufid_blog',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/dimasmufid_blog',
                'lib_path': 'dimasmufid_blog'},
  'syms': {'dimasmufid_blog.core': {'dimasmufid_blog.core.foo': ('core.html#foo', 'dimasmufid_blog/core.py')}}}
